const passport = require('passport');
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const User = require('../models/User');

/**
 * Google OAuth 2.0 strategy.
 *
 * Flow:
 *  - If a user with this googleId already exists -> log into that account.
 *  - Else if a user with this email already exists (e.g. they originally
 *    signed up with email/password) -> link googleId onto that existing
 *    account and log into it. This avoids a duplicate-key error on the
 *    unique `email` index and matches "If Google email already exists ->
 *    login existing account".
 *  - Else -> create a brand new account (role=user, balance=0,
 *    status=active, apiKey auto-generated by the User schema default,
 *    no password).
 *
 * NOTE: This only produces a Google profile on req.user for the single
 * callback request (see routes/authRoutes.js, which calls
 * passport.authenticate('google', { session: false, ... })). The app does
 * NOT use Passport sessions for authentication after this — authController
 * .googleCallback immediately issues the same JWT cookie used by normal
 * email/password login, and all subsequent requests are authenticated by
 * the existing middleware/auth.js `protect` middleware exactly as before.
 * serializeUser/deserializeUser below exist only so passport.session()
 * (loaded in server.js) doesn't throw if invoked; they are not part of
 * this app's real auth path.
 */
passport.use(
  new GoogleStrategy(
    {
      clientID: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      callbackURL: process.env.GOOGLE_CALLBACK_URL,
    },
    async (accessToken, refreshToken, profile, done) => {
      try {
        const email =
          profile.emails && profile.emails[0] && profile.emails[0].value
            ? profile.emails[0].value.toLowerCase().trim()
            : null;

        if (!email) {
          return done(new Error('Google account did not return an email address.'), null);
        }

        // 1. Already linked to this exact Google account.
        let user = await User.findOne({ googleId: profile.id });

        if (!user) {
          // 2. An account with this email already exists (e.g. signed up
          //    normally before) -> link it instead of creating a duplicate.
          user = await User.findOne({ email });

          if (user) {
            user.googleId = profile.id;
            await user.save();
          } else {
            // 3. Brand new user.
            user = await User.create({
              name: profile.displayName || 'Google User',
              email,
              googleId: profile.id,
              role: 'user',
              balance: 0,
              status: 'active',
              // password intentionally omitted - not required for Google users
              // apiKey uses the User schema's default generator
            });
          }
        }

        return done(null, user);
      } catch (err) {
        return done(err, null);
      }
    }
  )
);

passport.serializeUser((user, done) => {
  done(null, user.id);
});

passport.deserializeUser(async (id, done) => {
  try {
    const user = await User.findById(id);
    done(null, user);
  } catch (err) {
    done(err, null);
  }
});

module.exports = passport;
